[package]
name = "guess"
version = "0.1.0"
authors = ["Rob Sutherland <robert.c.sutherland.jr@saic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"